language: python
dist: xenial
python:
- 2.7
- 3.5
- 3.6
- 3.7
matrix:
  allow_failures:
  - python: 2.7
  - python: 3.5
install:
- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
- $HOME/.poetry/bin/poetry install -E flask
script: $HOME/.poetry/bin/poetry run py.test -v --cov=src --cov-report xml tests
before_deploy:
- $HOME/.poetry/bin/poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- $HOME/.poetry/bin/poetry build
deploy:
  provider: script
  script: "$HOME/.poetry/bin/poetry publish"
  skip_cleanup: true
  on:
    python: 3.7
    repo: uc-cdis/cdiserrors
    tags: true
env:
  global:
  - secure: IBigLx6AJaYEmXFPGqZqLTtVemknl4Ki9JMC/urwTbBcMr8uNgCVKyZzjPlZZwv73AvHAOE/gl56yFQeVVUi8TT9WFX8ovsMUad25GDRLfxTcUBeS4Ex8jGdTqvGTcvgIYEVti3Q48caVK5SPQLJEUu28oVuTja8Zx/YQmxcxOWwYd1UKhJQS7UAmSfN2O005yL7lmFlw0VMN5PgYdYCg2zd+1yK1Oyjz49Xf2TLkGd0XF6GREtc9ovhzxd+TdDitIePBjhQtaGDyYDfF3gEJuZ5lKglgknhP8WiG6YjDrXn9F5EXnea5eT+amNmhQ6OKxCY+aQNYvWH6KNrYjMSTazq4bi3TwPqGb8E0vmG2a+MCSTZh0SedzfhiDIp/3oHOLTAVwQ78OBZJBB11phBw+clASPfAHe6vnK9y0zLIKWtKFMVJiVWOPAlCe5y78zCXdvgDzrlQGIQlKfpmirH2gt2dn5Gsqbpp7I7iCTxgHW4aCf0tFB+BbVlfYcS77+Qa7s6gRnpMrAUED8aG29UMqq7a4Pwgz6fXnJkjxagz/nVR7GlJuPAQ2XxetPTbduAVpI6Nf9mEt96Y0ZRS1dPqPfP6R3R2QdhogkyqwTq7kpHflAnOAoolNCkytyGCHw56Azk4V/6a5vNfswfRVnBDZ5cElGWH8IycRwkLkuyVVQ=
  - secure: FzvNZNy70ciodT3qiDwwiiilTXRCzJLBc7bmEHpCiogyRsvzBgPiGUu8Q1OQBYw3H/2VWaBWXjGzewi8Hyr/yVJO0briWqjURgyhcaJheewYwowMw9T5hHrVxUn8kol0ruPf8SyuqbUy7D6uOWV5wxB0Jft3YhDvAVMerr32isa4RC3IvZ9J65rr+Ox2+8ev/6qKTR+ds5YykneVWx/NdRFZhnmbK8Bl0Pq5LIiS3jtLT3fnUJ4acum4yWgFEaR1WKNUYkpknosQSRZkdJanT/FuqBqzZuR/oQ+vx0ognrwwu4F1VYm1ICeKt/rhv6Og4dspjzLx3xAJY/kqV49YTREEFDiu9oMiIufDAk50BW1J4PMNHpodUDQ7fDe8o9mefUxZFxGEKLnEGzLH87o97QYm+o2HdnvHS53oRQkIZ8OoAfO25V1pWwL0TS4jcYOlSHkRK+RnE39MDeg3H9z1B0F91x4t50CGDC7tHoHvLfNBxs/C+CVUEY7SHIT7oiuBHEXLXldYf29b1nZbEaYxe/RXVqOvEocqYUWc4r1PKpe1T3N2YnQ1W3ibMvjY8lcrb/jhilMhg0l5Il5KM4dfGj2Q31HzkZ2F8yBebaRa7OZeh1CwpbYN6k/aBroQsXIWpsW3SqAHjF+xdBKIeHX2XHhBj/LJC/GO3OsLGNDs5PM=
  - secure: nPzmeWAs8sh5s/gfn6awwmoxB4mfJzrhmAqkVwpHhSTbMjJFTFSDqavTHNDE/zEO4fWjhObCsYdKTAWevxJqPgFqdRk67vou8iIXRqYfu9MYpm+Ab0d3h80/z61vnbh6YIllFfgFRh2q8Tlwu7t60jsEy4UX2j2Dx+JI71GgpKb7nHYzKvk4gyI5IHs/yWS5U893PUpyh7FAAvZ0uO65vd92Z8ANCZX34t7mFXevssCpeVI2l9ZHS+lvHf6vNJK5S1uj8bhRiVpd0Tf2eVX3uwDvtomlkcJbHSGx4G67D4NsWbRZZZ4YYZgq9+ASWmv4EexCv5k1fM11PaPJUYZ8sTf7TUsQ1B600atIvJNPGcA6d/iFijelUpoyFz5Ok9JIi84LlpSJ8pKONaaW6x7+DOtEGbbP773Lr1Pta8puDZbVwfPx8DGlUVDvAiKr8r92jOXFfmmTed8YobpeanEVeLuIUWD1EaN/kV18fI3HwgnpQ4kMX6alL479uk2uA6oDnvRecpFGzQScKgWEFWPet4exavRVy9q1B7w6JaPPoUwTK8Z651ItiZt4HWMcyVJ6BXjKu+1rE8HUsMVQ084bxM0j+7gnA6snJCOwOSCWPWp/9k2HvURcuOMWjksiAs2i4VSL3bUmMCAt7Ucf/Mt5YxYrJ82qy5Bw737mujXWGDs=
after_deploy:
- "./release_notes.sh"
