language: python
dist: xenial
python:
- 2.7
- 3.5
- 3.6
- 3.7
install:
- pip install pipenv
- pipenv install --dev
script: pipenv run py.test -v
deploy:
  provider: pypi
  user: uc-ctds
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: Dkzwpu2OfipscBk47kUp1qRd09yG5inSY1/6NU2H4S6Ekb0SnPX6aC0W03r7TdL/bUhYw9WraxCcrtmc5r1I6BxQpk8xjyib42wtzR+dQ0EDmh7GdlJ1HQ5Q8WJBPpdSDyHu8nvwdZzVINTw8Dww7nJp5SxP/DuTU9qm4egekdK7CxqBoN6HkyvXFf0LpgjnejTdN3PC0+USWjm5jbvhln9+r0f5hAKoAZjqHLBS3z0ernYQOL6qwoD+pXfsOPo7r+WiiHy2nZJ5Lf1LgeXVCXtt7G7viBNSSUTlabAmhd/dGEipoaEyxcojy5FpTtMoKQTuR/gWe0yFFoJEU7yI7Km4hEVzUhQOvan8elirE6Yw4+rZ83705sDerhxuZe9qarSxMX5Vwv4LclRnzYVJzxo7zn4TutbbTVFxol3HxRapSPs1A+5jky61rE53I4FyOj3/IY66HQoigmKWlKOPh1Yz42vyNG5E8CfqBJ+4vFt6kGZ7oFGDYCdcagn6sWSnfkeBQP9LLKEs9jumMA6ZNHOh8iGj7Q1jWcwI6/sJqjmrgdlTbhvsr0qxo1DalBSVa6rNaY4/3lFh6PxZDuVhmJtSoElYMxWuCzPnnKJeqQ2eLG1wm7q8QFmaVpiaRHlzqCJU5MLbgVcVkZI+T/5eULfCor+6VLjy9ev7ql4qZog=
env:
  global:
    secure: IBigLx6AJaYEmXFPGqZqLTtVemknl4Ki9JMC/urwTbBcMr8uNgCVKyZzjPlZZwv73AvHAOE/gl56yFQeVVUi8TT9WFX8ovsMUad25GDRLfxTcUBeS4Ex8jGdTqvGTcvgIYEVti3Q48caVK5SPQLJEUu28oVuTja8Zx/YQmxcxOWwYd1UKhJQS7UAmSfN2O005yL7lmFlw0VMN5PgYdYCg2zd+1yK1Oyjz49Xf2TLkGd0XF6GREtc9ovhzxd+TdDitIePBjhQtaGDyYDfF3gEJuZ5lKglgknhP8WiG6YjDrXn9F5EXnea5eT+amNmhQ6OKxCY+aQNYvWH6KNrYjMSTazq4bi3TwPqGb8E0vmG2a+MCSTZh0SedzfhiDIp/3oHOLTAVwQ78OBZJBB11phBw+clASPfAHe6vnK9y0zLIKWtKFMVJiVWOPAlCe5y78zCXdvgDzrlQGIQlKfpmirH2gt2dn5Gsqbpp7I7iCTxgHW4aCf0tFB+BbVlfYcS77+Qa7s6gRnpMrAUED8aG29UMqq7a4Pwgz6fXnJkjxagz/nVR7GlJuPAQ2XxetPTbduAVpI6Nf9mEt96Y0ZRS1dPqPfP6R3R2QdhogkyqwTq7kpHflAnOAoolNCkytyGCHw56Azk4V/6a5vNfswfRVnBDZ5cElGWH8IycRwkLkuyVVQ=
after_deploy:
- ./release_notes.sh
