language: python
dist: xenial
python:
- 2.7
- 3.5
- 3.6
- 3.7
matrix:
 allow_failures:
   - python: 2.7
install:
- pip install pipenv
- pipenv install --dev --deploy
script: pipenv run py.test -v
deploy:
  provider: pypi
  user: uc-ctds
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: EQXjzvRmew4OukFupk9jUaE+X5IZnri2bCxNGisKvoRmfj/JaXEMjjFMTLlXiC9S9vIMaAP9fcxtJrZVIZUnBe5JZMPxGEg6RZieC7d9sVKLsv7ugLhly4UjPoR6Jg2KlwBUuANr6svrzdg3kXulMXotmhxtB6GEZNMmsgJONMxNORrpkE2tfyu4Mxnzimec708hRvlp+Ph/tq9xTZztEJyXNDm+tCsyrRtFDGEKrxrwBrMsXYMPK6smuJMfK60VxMpoVrNpEMZwbpDS1gxpLk362g17844Rx/NAisg0xGlOdPjkpgj7tdeLsTdI5S8PLB299qaaKnDVSULguLaY4fz7g64oR2Uzn/wpvb0ZvHgGCsq8c597Db+LEyCRUhP2rvd02hZZLIIIAEP6QSncG1i7VE53n+D3ohe8ipRErXvfx4rXr45fkFe1i+0HpFgApSf42fxJMbmAl5Q7CHjYGz5w653sRb2/y0Vj2RjSL3abDZwhTKn2sUNw47PszG5O8fqnXESEdFj9B6bIHOYApcrLaBw3GirPQut0xITAy++/Ta/pJQL3GsgCbl4gJYWFO1wvQs2UXKwH5RlH8TwsC1y4bD46phoBiXcNSeA97vdb6N5pAjpBIKs220cemNF8AHMy9fSSaRUceySGfRCLOf1fHIsSKWaY05lalr2UxkE=
env:
  global:
    secure: IBigLx6AJaYEmXFPGqZqLTtVemknl4Ki9JMC/urwTbBcMr8uNgCVKyZzjPlZZwv73AvHAOE/gl56yFQeVVUi8TT9WFX8ovsMUad25GDRLfxTcUBeS4Ex8jGdTqvGTcvgIYEVti3Q48caVK5SPQLJEUu28oVuTja8Zx/YQmxcxOWwYd1UKhJQS7UAmSfN2O005yL7lmFlw0VMN5PgYdYCg2zd+1yK1Oyjz49Xf2TLkGd0XF6GREtc9ovhzxd+TdDitIePBjhQtaGDyYDfF3gEJuZ5lKglgknhP8WiG6YjDrXn9F5EXnea5eT+amNmhQ6OKxCY+aQNYvWH6KNrYjMSTazq4bi3TwPqGb8E0vmG2a+MCSTZh0SedzfhiDIp/3oHOLTAVwQ78OBZJBB11phBw+clASPfAHe6vnK9y0zLIKWtKFMVJiVWOPAlCe5y78zCXdvgDzrlQGIQlKfpmirH2gt2dn5Gsqbpp7I7iCTxgHW4aCf0tFB+BbVlfYcS77+Qa7s6gRnpMrAUED8aG29UMqq7a4Pwgz6fXnJkjxagz/nVR7GlJuPAQ2XxetPTbduAVpI6Nf9mEt96Y0ZRS1dPqPfP6R3R2QdhogkyqwTq7kpHflAnOAoolNCkytyGCHw56Azk4V/6a5vNfswfRVnBDZ5cElGWH8IycRwkLkuyVVQ=
after_deploy:
- "./release_notes.sh"
